baseURL = 'https://breakingnewsnetwork.com'
languageCode = 'en_US'
timeZone = 'America/New_York'
title = 'Breaking News Network'
theme = 'bnn'
enableRobotsTXT = true

[markup]
  defaultMarkdownHandler = 'goldmark'
    [markup.goldmark]
      [markup.goldmark.parser]
        [markup.goldmark.parser.attribute]
          block = true
          title = true