baseURL = 'https://breakingnewsnetwork.com'
languageCode = 'en-US'
title = 'Breaking News Network'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Subscribe'
pageRef = '/subscribe'
weight = 20

[[menus.main]]
name = 'Incidents'
pageRef = '/incidents'
weight = 30

[[menus.main]]
name = 'Terms & Conditions'
pageRef = '/terms-and-conditions'
weight = 40

[[menus.main]]
name = 'Privacy Policy'
pageRef = '/privacy-policy'
weight = 50

[[menus.main]]
name = 'Contact Us'
pageRef = '/contact-us'
weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


